### ISSUE TITLE
User view a list of contacts.

### ISSUE THREAD

**Issue by riley-rangel** [riley-rangel/contacts#1]
# Motivation
Users need to be able to view their saved contacts.

# Implementation
- [x] Set up simple API with route to return mock contacts.
- [x] Define `Header` component for app.
- [x] Create `contactsAPI.js` to access the custom contacts API.
- [x] Define `ContactList` component to render out a list of contacts. 
- [x] Define a `Contact` component to render an individual contact object.
- [x] Have the `App` component request the contacts list on load.
- [x] Add contacts to app state for time-being.
- [x] Pass contacts array down so they can be rendered by the `ContactList`.
- [x] Make any styling adjustments to improve visual appeal.

**Comment by hoshikitsunoda** [comment]
hey Riley, sorry for stalking but i just saw this repo on my feed.
I saw this article this morning. Azure seems fun to play with and might be good for this project:

https://css-tricks.com/create-your-own-serverless-api/

**Comment by riley-rangel** [comment]
thanks @hoshikitsunoda I'll take a look
